#!/usr/bin/env bash
# Lint driver for the MiG Alley tree.
#
#   scripts/lint.sh              all compiled sources (slow; legacy code is noisy)
#   scripts/lint.sh FILE [...]   only the given source files
#   scripts/lint.sh -c FILE      clang-check (syntax/AST parse) only
#   scripts/lint.sh -p FILE      cppcheck only
#
# Deliberately clang-check + cppcheck only — NO clang-tidy anywhere:
# tidy rewrites encourage modernisation and make diffing against the
# original 1998 source harder.
#
# Requires compile_commands.json in build/ (generated by default -
# CMAKE_EXPORT_COMPILE_COMMANDS is ON). clang-check gets the exact
# per-file compile flags from it.
#
# Exit status: non-zero if any tool failed to run or emitted an "error:"
# diagnostic; warnings/notes are printed but do not fail the script.
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUILD="${BUILD_DIR:-$ROOT/build}"
CC_DB="$BUILD/compile_commands.json"
MODE=all

case "${1:-}" in
    -c) MODE=check; shift ;;
    -p) MODE=cpp;   shift ;;
esac

if [ $# -gt 0 ]; then
    FILES=("$@")
else
    [ -f "$CC_DB" ] || { echo "no $CC_DB - configure the build first"; exit 2; }
    mapfile -t FILES < <(python3 -c "
import json,sys
for e in json.load(open('$CC_DB')): print(e['file'])" | sort -u)
fi

INC="-I$ROOT/H -I$ROOT/MFC"
DEF="-D__GNUC__ -DNDEBUG"
# SDL_config.h pulls in the i386 multiarch header; add it if the compile
# database lacks it (e.g. a build dir configured without the sysroot flags)
EXTRA=""
MARCH_INC="$ROOT/../../sysroot-i386/usr/include/i386-linux-gnu"
[ -d "$MARCH_INC" ] && EXTRA="-extra-arg=-I$(cd "$MARCH_INC" && pwd)"
FAILED=0

run_tool() {
    # $1 = label, rest = command. Full output is kept; "error:" lines or
    # a non-zero tool exit mark the run as failed.
    local label="$1"; shift
    local out rc
    out="$("$@" 2>&1)"; rc=$?
    if [ -n "$out" ]; then
        echo "$out"
    fi
    if [ $rc -ne 0 ]; then
        echo "lint: $label exited $rc"
        FAILED=1
    elif printf '%s\n' "$out" | grep -q 'error:'; then
        FAILED=1
    fi
}

for f in "${FILES[@]}"; do
    [ -f "$f" ] || f="$ROOT/$f"
    [ -f "$f" ] || { echo "skip (missing): $f"; continue; }
    echo "== $f"
    if [ "$MODE" = check ] || [ "$MODE" = all ]; then
        run_tool clang-check clang-check -analyze -p "$BUILD" $EXTRA "$f"
    fi
    if [ "$MODE" = cpp ] || [ "$MODE" = all ]; then
        run_tool cppcheck cppcheck --enable=warning,performance,portability \
            --inline-suppr -q $INC $DEF "$f"
    fi
done
exit "$FAILED"
